export const projects = [
  {
    id: "texttools",
    name: "Text Tools",
    path: "/texttools",
    icon: "\u{1F527}",
    description: "Format JSON, convert case, trim, Base64 encode/decode",
  },
  {
    id: "spritesheetslicer",
    name: "SpriteSheet Slicer",
    path: "/spritesheetslicer",
    icon: "✂️",
    description: "Slice spritesheet images into grid pieces and download as ZIP",
  },
  {
    id: "color",
    name: "Color Tools",
    path: "/color",
    icon: "\u{1F3A8}",
    description: "Convert colors, generate palettes, check WCAG contrast",
  },
  {
    id: "freegames",
    name: "Free Games",
    path: "/freegames",
    icon: "\u{1F3AE}",
    description: "Free games on Steam & Epic Games Store",
  },
  {
    id: "spritesheetviewer",
    name: "SpriteSheet Viewer",
    path: "/spritesheetviewer",
    icon: "🎞️",
    description: "Animate sprite frames, adjust FPS and loop modes",
  },
  {
    id: "texturepacker",
    name: "Texture Packer",
    path: "/texturepacker",
    icon: "🧩",
    description: "Pack image assets into sprite sheets with plist metadata",
  },
  {
    id: "poe2",
    name: "POE 2",
    path: "/poe2",
    icon: "\u{1F3F9}",
    description: "Regex tools, market check, and notes for Path of Exile 2",
  },
  {
    id: "staticpages",
    name: "Static Pages",
    path: "/staticpages",
    icon: "\u{1F4C4}",
    description: "Browse standalone HTML pages and mini projects",
  },
  {
    id: "timeline",
    name: "Timeline",
    path: "/timeline",
    icon: "\u{1F4C5}",
    description: "Vietnamese event timeline with lunar calendar",
  },
  {
    id: "ptimeline",
    name: "Personal Timeline",
    path: "/ptimeline",
    icon: "\u{1F4CB}",
    description: "Personal event timeline with CRUD and lunar calendar",
    auth: true,
  },
  {
    id: "telegram",
    name: "Telegram",
    path: "/telegram",
    icon: "\u{1F4AC}",
    description: "Send messages via Telegram Bot API",
    auth: true,
  },
  {
    id: "bookmarks",
    name: "Bookmarks",
    path: "/bookmarks",
    icon: "\u{1F516}",
    description: "Tabbed bookmark manager",
    auth: true,
  },
  {
    id: "youtube",
    name: "YouTube",
    path: "/youtube",
    icon: "\u{1F4FA}",
    description: "Track YouTube channels and videos",
    auth: true,
  },

];
