export const projects = [
  {
    id: "texttools",
    name: "Text Tools",
    path: "/texttools",
    icon: "\u{1F527}",
    description: "Format JSON, convert case, trim, Base64 encode/decode",
  },
  {
    id: "spritesheetslicer",
    name: "SpriteSheet Slicer",
    path: "/spritesheetslicer",
    icon: "✂️",
    description: "Slice spritesheet images into grid pieces and download as ZIP",
  },
  {
    id: "color",
    name: "Color Tools",
    path: "/color",
    icon: "\u{1F3A8}",
    description: "Convert colors, generate palettes, check WCAG contrast",
  },
  {
    id: "bookmarks",
    name: "Bookmarks",
    path: "/bookmarks",
    icon: "\u{1F516}",
    description: "Tabbed bookmark manager",
    auth: true,
  },
  {
    id: "tasks",
    name: "Tasks",
    path: "/tasks",
    icon: "✅",
    description: "Task manager with Telegram reminders",
    auth: true,
  },
  {
    id: "timeline",
    name: "Timeline",
    path: "/timeline",
    icon: "\u{1F4C5}",
    description: "Vietnamese event timeline with lunar calendar",
  },
  {
    id: "telegram",
    name: "Telegram",
    path: "/telegram",
    icon: "\u{1F4AC}",
    description: "Send messages via Telegram Bot API",
    auth: true,
  },
  {
    id: "youtube",
    name: "YouTube",
    path: "/youtube",
    icon: "\u{1F4FA}",
    description: "Track YouTube channels and videos",
    auth: true,
  },
  {
    id: "facebook",
    name: "Facebook",
    path: "/facebook",
    icon: "\u{1F4D8}",
    description: "Track Facebook pages and fetch posts via RSS Bridge",
    auth: true,
  },
];
